user_list =[{'first_name': 'Anton', 'last_name': 'Ivanov', 'user_name': 'Aersum'},
{'first_name': 'Anton', 'last_name': 'Dotsenko', 'user_name': 'None'}, 
{'first_name': 'Roman Zhovna', 'last_name': 'None', 'user_name': 'None'}, 
{'first_name': 'Eugene', 'last_name': 'Zabolotny', 'user_name': 'eugenezabolotny'},
{'first_name': 'Viktor', 'last_name': 'B.', 'user_name': 'sancheezzz'}, 
{'first_name': 'Roman', 'last_name': 'Buryy', 'user_name': 'None'}, 
{'first_name': 'Дмитро', 'last_name': 'Bragarnik', 'user_name': 'Sarbai'}, 
{'first_name': 'Alexandr', 'last_name': 'Klimach', 'user_name': 'klimach'}, 
{'first_name': 'Ostap', 'last_name': 'Rodomansky', 'user_name': 'ostap_rodomansky'},
{'first_name': 'Igor', 'last_name': 'Tagintsev', 'user_name': 'Ingvar1390'},
{'first_name': 'Dmytro', 'last_name': 'Melnyk', 'user_name': 'Ekut_v'}, 
{'first_name': 'Arthur', 'last_name': 'Veres', 'user_name': 'Artooi'},
{'first_name': 'Ruslan', 'last_name': 'Karelov', 'user_name': 'None'},
{'first_name': 'Almost wise', 'last_name': 'Dragon', 'user_name': 'AlmostWise'},
{'first_name': 'Olga', 'last_name': 'Tregub', 'user_name': 'None'},
{'first_name': 'Yevheniia', 'last_name': 'Kyryliuk', 'user_name': 'EvgeniaCURSOR'},
{'first_name': 'Pavlo', 'last_name': 'Kandiak', 'user_name': 'kandiak_ps'},
{'first_name': 'Maxim', 'last_name': 'Poleshko', 'user_name': 'Maxsim_P'},
{'first_name': 'Alexander', 'last_name': 'Kozhokar', 'user_name': 'hey_alex'},
{'first_name': 'Андрій', 'last_name': 'Станішевський', 'user_name': 'xlibchyk'},
{'first_name': 'Bohdan', 'last_name': 'Novakivskyy', 'user_name': 'None'},
{'first_name': 'Eugene', 'last_name': 'Semanyshyn', 'user_name': 'None'},
{'first_name': 'Igor', 'last_name': 'None', 'user_name': 'siriusnlo'},
{'first_name': 'Anna', 'last_name': 'None', 'user_name': 'None'},
{'first_name': 'Misha', 'last_name': 'Antonkin', 'user_name': 'Cosmander'},
{'first_name': 'Jenia', 'last_name': 'Trofimenko', 'user_name': 'jeniaTrofimenko'},
{'first_name': 'Albert', 'last_name': 'Li', 'user_name': 'None'},
{'first_name': 'Alina', 'last_name': 'Brygas', 'user_name': 'None'},
{'first_name': 'Andrii', 'last_name': 'Homeniuk', 'user_name': 'None'},
{'first_name': 'Igorosha', 'last_name': 'Prorochuk', 'user_name': 'None'},
{'first_name': 'Natali', 'last_name': 'Maslova', 'user_name': 'None'},
{'first_name': 'Eugen', 'last_name': 'None', 'user_name': 'None'},
{'first_name': 'Roman', 'last_name': 'Rodomansky', 'user_name': 'romanrodomansky'}]
if __name__ == "__main__":
    print(list(user_list[0].keys()))